### ISSUE TITLE
How have you made the datasets ready?

### ISSUE THREAD

**Issue by meincv** [chufengt/iccv19_attribute#4]
Could you please explain about the dataset preparation.
Is it similar to this project? (https://github.com/dangweili/pedestrian-attribute-recognition-pytorch)

I used this script (https://github.com/dangweili/pedestrian-attribute-recognition-pytorch/blob/master/script/dataset/transform_peta.py) to prepare the `peta` dataset. It is producing a `.pkl` file. But, in your codes, you don't analyze `.pkl` files!

What should be the type of the `label` in the `__init__` function of the `MultiLabelDataset` class?

I appreciate your clarification about dataset preparation.

**Comment by chufengt** [comment]
Yes, it's not exactly the same as dangweili's project, but they provide a good example.

The `label` in `MultiLabelDataset ` class means the file that encoding the mapping between image name and its ground-truth (GT vector should contain only 0 or 1 values).

For PETA and PA-100K, they provide the same format, just download it from the official websites (be careful about GT values since some of them using -1 or 1).
For RAP, they only provide `.mat` files, which need to be processed according to their `ReadMe.txt` (sorry I can't find my scripts but it's not difficult).

**Comment by chufengt** [comment]
I've uploaded the label lists.

**Comment by eeric** [comment]
> Could you please explain about the dataset preparation.
> Is it similar to this project? (https://github.com/dangweili/pedestrian-attribute-recognition-pytorch)
> 
> I used this script (https://github.com/dangweili/pedestrian-attribute-recognition-pytorch/blob/master/script/dataset/transform_peta.py) to prepare the `peta` dataset. It is producing a `.pkl` file. But, in your codes, you don't analyze `.pkl` files!
> 
> What should be the type of the `label` in the `__init__` function of the `MultiLabelDataset` class?
> 
> I appreciate your clarification about dataset preparation.

https://github.com/chufengt/iccv19_attribute/issues/37

**Comment by eeric** [comment]
https://github.com/chufengt/iccv19_attribute/issues/37
